ProjectName = "dummy_proj"
Author = "May Draskovics"
ProjectPath = ""
DueDate = "not_set"
MainFile = "main.py"
TestScript = "test.py"
Executable = "python"
ProjFiles = ["project.toml", "main.py", "test.py"]
ExpectedOutPuts = ["hello", "world"]
RequiredPasses = 0
TimeOutAfterSeconds = 99999
CountExecutionAsPass = true
