AppVersion = "v1.0"
AppAuthor = "May Draskovics"
AppAPI = "something.com"
AutoUpdate = false

[Projects]
  [Projects.""]
    Name = ""
    Owner = ""
    TomlPath = "D:/github/ProjectPacker"
  [Projects.dummy_project]
    Name = "dummy_project"
    Owner = "May Draskovics"
    TomlPath = "D:/github/ProjectPacker"

[Modules]

[Templates]
  [Templates.test]
    Name = "test"
    Language = "python"
    Path = "C:/Users/Cross/AppData/Roaming/project_packer/test.py"
